language: java
jdk: oraclejdk8
install: true
before_script:
  - chmod +x ./gradlew
script:
  - "./gradlew build --parallel -s"
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
deploy:
  provider: bintray
  user: fangzhengjin
  key:
    secure: vDZj0NJbuYP9KDNtaIj8Im1PtlOZtMoNQEUHDwPWuaX9jW2m3Dzx+8wac3AyIfskO6hbyYj3YBUOyrxBg9qx7Zs7SETPMWmmswhP0cr5DbuuMIyKuTL+y5e/yL3iNo008vT0EQMUO3e1yVBQzYv/b5JSVE5I4dbcsgVDsQFgWwTXlzDoECqAJBYxhP0slNSguDXjQXDJQfZrMdjxYrK/HqFU5YYQiUu9j2e/mI0TlghwccPXvFUyOdFYbMX4061wdxuMfYBQmsuTzUEgLCBI3NceTjCPcouem7k3SgfGNS6fV6M/zpAcu3I/FRE38D5O4yqPKPl27cpg/hgOP/q53/1bd3aURqRnWHYmH4NOtFmArAoXydCiGBDdZtgwamoCKnS2PnoJ98O6MkV9G4UbSPHKbd2rXoBxB+kN0G8wEz3cP618qzWsoHndsYZMDY/JjFd8Me/DaBBfv+R2osDiJx1S3qZk6dFHwWZ5Oyhdaq8kd5rN/VQhsc+T836+E0ejOpcmka7IGW83MuZJ8u/dIaPQLQJMxD43rBqIB8y83KZp5wZJhrx/crbxYZJe1IdmgU7MZ+vvEx5119PU65wkWd/poS6SdY3MVk6hK0K9xoeMQ7R32mmBK8kEwerolpYdsv3FVNZRg9HIGLr14s0Fhlyi2nmMtSmqpYYLSpjU+Xk=
  skip_cleanup: true
  file: build/descriptor.json
  on:
    tags: true
    jdk: oraclejdk8
    branch: master
